### ISSUE TITLE
attack rolls, midi QOL compatibility

### ISSUE THREAD

**Issue by JerryTheMac** [Yosoy-Ed/critic-message#1]
currently i cant manage to make the module drop the message while using an attack roll. 
that being said, is there a way to make this happen and if so, can we have a different list for attacks? so that maybe we can populate this list with critical hits and fails for a combat situation?

**Comment by Yosoy-Ed** [comment]
Which system and versions are you using? 

I am playing pf2e on foundry v11 only without issues, I haven't checked other systems. 

About the separated lists I guess it is possible, but I prioritize pf2e, other systems may handle it different and will be done after.

**Comment by JerryTheMac** [comment]
D&D 5e 3.2, Foundry v11

**Comment by Yosoy-Ed** [comment]
> D&D 5e 3.2, Foundry v11

I just updated with the suggestion to separate attacks from other rolls, I am going to test now D&D, I am not playing it but I will try to keep compatibility.

**Comment by Yosoy-Ed** [comment]
Update 0.1.4 should be working on DnD 5e 3.2.1, Foundry v11. 

I will close the issue, feel free to reopen it if your issue persist.

**Comment by JerryTheMac** [comment]
sorry me again :D thanks for the 2 separate lists. 

looks like there is a compatibility issue when using together with "Midi QOL"
I've tested with and with out Midi enabled, and when it is, the attack crit/fumble picture messages wont pop in chat. ive been testing all kinds of settings within Midi QOL, but i cant get both modules to work together during attack rolls. 

so if you ever have a chance to check why this would happen, id appreciate it :D thanks!

**Comment by Yosoy-Ed** [comment]
I installed MidiQOL, with default settings I see the message triggering as normal. I have no idea what is Midi doing on your side or what settings do you have enabled. Google tells me Midi is very popular on DND 5e, without more info it is hard to debug as I don´t play it. 

Do you see any message on console when you roll a nat20 or nat1?

![image](https://github.com/user-attachments/assets/ef1ae694-c3f9-4432-929e-c56deaf9520b) 
![image](https://github.com/user-attachments/assets/8449e1a9-9386-48b2-938c-97b56026445a)

**Comment by JerryTheMac** [comment]
![Foundry_Virtual_Tabletop_MQQ6KGH9a4](https://github.com/user-attachments/assets/ff01f84d-b8d8-4dd1-86e5-d6c16608e932)
looks like every attack triggers the same console message. being nat 20 or normal. 
in the case of the current attacker im using, with modifiers 26 is the "nat 20"

someone in the Midi Discord server said:
_MidiQOL changes the Chat Message, so probably that module is expecting something that is not there.
It's easy to do that with a small World script though too._

I sadly dont know what would that imply. 
I also opened a "tiket" on their discord about this.

**Comment by Yosoy-Ed** [comment]
> looks like every attack triggers the same console message. being nat 20 or normal. in the case of the current attacker im using, with modifiers 26 is the "nat 20"
> 
That error does not seems to affect this module... I guess...

> someone in the Midi Discord server said: _MidiQOL changes the Chat Message, so probably that module is expecting something that is not there. It's easy to do that with a small World script though too._
> 
Exactly, the module reads the chat message to get the required data, but it seems Midi changes its structure based on his settings, because default settings is working on my side.

you can export your module settings with [Foriens Copy Environment](https://foundryvtt.com/packages/forien-copy-environment/) so I can compare and check if I can add compatibility

**Comment by JerryTheMac** [comment]
![Foundry_Virtual_Tabletop_LNelwNCz4l](https://github.com/user-attachments/assets/a2dba3f2-b0ea-4a0e-9b73-cc92a24b10de)

![Foundry_Virtual_Tabletop_CHslzYsdk8](https://github.com/user-attachments/assets/7e22d691-3378-4c77-a47a-9d1e2951bb34)

created a new wolrd, only enabled the most important modules I use, and i started attacking till i got a crit, the log looks the same on all attacks, stil
also tried rolling d20s which before triggered your module, now they dont, and i get this error. 

the only time the crit messages work is with skill checks. 

[foundry-settings-export-2024-07-16-20-43-42-cheese-copy.json](https://github.com/user-attachments/files/16258604/foundry-settings-export-2024-07-16-20-43-42-cheese-copy.json)
[module list.txt](https://github.com/user-attachments/files/16258605/module.list.txt)

**Comment by Yosoy-Ed** [comment]
Ok, those errors are fixed now. 
But still looking on how to add the compatibility as midi changes ~disable~ mess with the chatmessage inside the hooks I use. It is a massive mod.

**Comment by JerryTheMac** [comment]
might have to wait till they answer my ticket on discord then, thanks :)
ill keep you posted.

**Comment by Yosoy-Ed** [comment]
Ok, testing on my side is working with new update 0.1.5, let me know if you find any issues.
